### ISSUE TITLE
sp_pressuredetector and sp_humanevents

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#1062]
Can we have sp_pressuredetector as a report or use it for pulling wait stats? it is written by Erik Darling and he is one of the best performance tuner in the world. He has also HumanEvents which is the best in-depth blocking analysis I have ever seen.

**Comment by DavidWiseman** [comment]
Thanks for the suggestion.  DBA Dash already tracks wait stats and it has the advantage of being able to do this over time rather than since service start.  

I do think sp_PressureDetector is a useful tool though, but for interactive use rather than for regular collection.  Being able to trigger this from DBA Dash would be cool though and it's possible with the [messaging](https://dbadash.com/docs/help/messaging/) feature that was added. 

I would like to add support for triggering community scripts like sp_PressureDetector and sp_HumanEvents on demand.  I've thought about doing so for some of the FRK scripts. It's not on my immediate radar but it might get implemented at some point.

**Comment by DavidWiseman** [comment]
Included in [3.13](https://dbadash.com/blog/whats-new-in-3.13/) 🎉

**Comment by aachaemenes** [comment]
Loving it.
