### ISSUE TITLE
Low contrast text in running queries snapshot with Dark theme

### ISSUE THREAD

**Issue by emanuelearena** [trimble-oss/dba-dash#1106]
Hello,
I'm on version 3.13, dark theme, and in the Running Queries panel, specifically in the snapshot view, I got a low-contrast text. This makes data hard to read. In previous versions, I was able to view the data correctly.

![Issue low visibility](https://github.com/user-attachments/assets/3d1c0683-ac91-46d6-8549-bfe181d19b8a)

Thank you for this great software!

**Comment by DavidWiseman** [comment]
Hi,

Thanks for reporting this issue.  The grid was replaced everywhere which adds new filtering options.  It looks like the running queries is explicitly specifying the link color for the columns and it's no longer overriding this with the selected theme.  I'll get this fixed in the next release.

Thanks,

David

**Comment by DavidWiseman** [comment]
Fixed in 3.13.1 🎉
