### ISSUE TITLE
Sort Waits by Instance Tool Tip

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#213]
Could we sort the Tool Tip on the Waits: Instance graph on the Performance tab descending by %?  That would make it easier to see which waits are the heaviest in sequence.

![image](https://user-images.githubusercontent.com/29784949/171170830-71b2a805-f594-4524-afd2-a265727b7c86.png)

**Comment by DavidWiseman** [comment]
Hi,  thank you for the suggestion.
The sort order is based off the data returned from this query:
https://github.com/trimble-oss/dba-dash/blob/main/DBADashDB/dbo/Stored%20Procedures/Waits_Get.sql
I know the query could be altered to return the waits by total wait for the whole period.  So the top wait could be listed first but this would be the top wait for the hour rather than the 2min period you are hovering over.  The top wait might not always be listed first and the order might appear more random if there is a bit of variation in the waits.  
I'm not sure if it's possible to change the sort order on a per period basis - at least not without some work.

I might consider improvements to this as part of issue #35.

**Comment by DavidWiseman** [comment]
Wait tooltip will now be sorted by total wait time.  This will be the overall wait rather than the wait time for each period.  The top 3 waits will also be listed in the title bar. 
#508

**Comment by DavidWiseman** [comment]
Included in 2.33.0 🎉
