### ISSUE TITLE
Add support for DBADash database in AlwaysOn Availability Group

### ISSUE THREAD

**Issue by tvanzeleDelen** [trimble-oss/dba-dash#273]
I installed the dbadash database in an AG, but there is no option to set the MultiSubnetFailover parameter, so from time to time we get an unhandled exception because of a time-out.

**Comment by DavidWiseman** [comment]
In the service configuration tool you can edit the destination connection string and manually and add:
`;Multi Subnet Failover=True`

Note: I don't have the DBA Dash repository DB in an availability group, but I do have some AGs which are monitored by DBA Dash.  Each node in the AG is added as source connections in DBA Dash rather than the listener.
