### ISSUE TITLE
Calculation issue?

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#314]
I believe I found a calculation issue which may cause Panic in some situations :D. Review the image for details. I have already checked the server, disk and log file size and so on.

![filegroup_free](https://user-images.githubusercontent.com/40255900/191679982-38f27a59-9c33-4a5e-88cb-113f791a2bfe.png)

**Comment by DavidWiseman** [comment]
Hi,

This is by design with the default configuration but you can change it.  Your log file has used almost all of the available space and will need to grow if it's not able to reuse the existing space soon.  Expanding log files can have a performance impact as it needs to zero out the space (instant file initialization doesn't apply to logs).  The performance impact will depend on the growth amount, the speed of your drives, and how often it needs to grow.   It's probably not a huge impact but it's better to have the space pre-allocated so it only grows in exceptional circumstances.  A growing log file could indicate a long-running open transaction that might need to be investigated.

You could configure DBA Dash to only alert you if the log file has auto growth disabled.  This is the default for data files.  

- Select configure root threshold. (Or it can be configured at the database or instance level)
- Click the Log tab.
- Check zero autogrowth only

![image](https://user-images.githubusercontent.com/33157668/191692868-9b8af499-71ae-41a3-93f7-4d3f15310e84.png)

Hope this helps

**Comment by DavidWiseman** [comment]
Thank you 😊
