### ISSUE TITLE
error uploading reports

### ISSUE THREAD

**Issue by tune007** [trimble-oss/dba-dash#364]
Hi, I am getting this error when trying to upload the dbadash reports. I tried on SSRS2019 and SSRS2017 Can you please advise how to work around this error:

The definition of this report is not valid or supported by this version of Reporting Services. The report definition may have been created with a later version of Reporting Services, or contain content that is not well-formed or not valid based on Reporting Services schemas. Details: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

**Comment by DavidWiseman** [comment]
The target version is SQL 2016 or later so they should work with 2017 or 2019.  How are you deploying the reports - if using visual studio it might be worth checking for updates to the reporting service extension.  I'm using VS 2022 with the reporting services projects 2022 extension.

Note: The SSRS reports are no longer been maintained.  I recommend using the DBADash.exe windows app instead.  I will consider pull requests if there is interest from the community in supporting and maintaining the SSRS reports.

**Comment by tune007** [comment]
Thanks David, appreciate the quick response. I also tried deploying with VS2022 and reporting services projects 2022 extension. Appreciate the quick response :)

**Comment by DavidWiseman** [comment]
I'm not sure what the issue is.  You could see if uploading the files via the web interface works - not the best way to deploy the reports but might be interesting to see if the error occurs.  
Hope you get it sorted - post back if you find a fix.  Again, I would recommend the Windows app as the front end as it's been some time since the SSRS reports have been updated.  They could be a good starting point if you were interested in maintaining them though.
