### ISSUE TITLE
Identity Column and the year 2162

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#369]
Hi,

this one is not a major problem but I think it is worth reporting (and correcting). Version used 2.22.8

As the image shows, in table values "Identity Columns" I discovered an edge case as shown in the image. The date values is empty (probably a NULL or out of range value, wrong date conversion etc.?). The estimated year would be around 2162 ! and according to MS Docx, "datetime" Type Date Range is from January 1, 1753, through December 31, 9999 so I guess someting has gone south here. The Tool Tip value is also wrong as there is noting to "Change/Edit".

I also couldn't really understand the **negative** values in the "Avg Rows/day" (I missed to mark them in the image). How can that be?

Anyways I think around 2162 there will be no need of DB Server anymore and probably our ancestors have found a different way to count identities or probably they aren't needed by then :D. 

![identity_column_estimated_date](https://user-images.githubusercontent.com/40255900/194170221-8c2d3748-8d3e-4dbe-8e8f-fe6d0d6e3bcf.png)

**Comment by DavidWiseman** [comment]
The estimated date is NULL if it's more than 100 years into the future.  This avoids overflowing the date type - it could be changed to more than 100 years if anyone has a use case for this...but it's probably going to be someone else's problem.

The Avg Rows/day and Avg Ident per day are just calculated by taking the oldest snapshot from within the last 31 days and subtracting it from the current snapshot.  So if your row count has gone down through deletes you will have a negative value.  You shouldn't get this with identity unless you reseeded.

It can be useful to track both.  If you reseed to a negative value because you were running out of identity values, just using identity counts things will look good.  The row count will highlight there is an issue (depending on deletes).  A more robust check could take into account the table's max/min values, but that would be expensive to collect and would only be useful in some edge cases.

**Comment by DavidWiseman** [comment]
It will show >100 years instead of NULL in the next release.
![image](https://user-images.githubusercontent.com/33157668/194414256-dc368757-dce3-4128-8de2-363835f8f7e6.png)

The default behaviour of the datagrid in .NET adds the Edit tooltip where there is a NULL value.  Or "Link" if it's a link column.  You can usually edit the items in the grid but editing is disabled as this data should be read-only.  Not worth the effort to add a custom tooltip to each grid column that might have nulls IMO.
