### ISSUE TITLE
Is it possible to limit the memory usage DBADashService

### ISSUE THREAD

**Issue by ArRiMartinez** [trimble-oss/dba-dash#476]
I am currently using DBADash with 19 connections.
The configuration for the moment is the default, with snapshot.
SQL versions range from 2005 to 2022.
The service runs in console mode with 10 threads.
The problem occurs in the memory consumption of the service, which starts at 200 Mb to 6 Gb, consuming 80% of the total.
**How to limit the memory consumption of the service to say 3 Gb.**

**Comment by DavidWiseman** [comment]
The memory usage seems unusually high.  My lab environment has 21 connections and the memory usage is ~140MB.  Another prod system I have access to is monitoring hundreds of connections and has less than 400MB.
Does the memory just slowly increase over time? How long does it take to get to 6GB?

Console mode is good to quickly test the application but otherwise I would recommend installing as a service.  Once it's installed, you can remove it easily with the Uninstall service link.  I don't think that it would cause higher memory usage in console mode.
![image](https://user-images.githubusercontent.com/33157668/207621485-7dd65e22-9b57-4495-992f-6e194d699d12.png)

If you are using schema snapshots do you have a database with a very large number of objects?  Or do you have a very large number of databases?  

There isn't any way to limit the memory usage as far as I'm aware - though there are probably some 3rds party tools that might be able to do this.  It might just brake the application though - ideally we need to identify where the memory is been used.

**Comment by ArRiMartinez** [comment]
Dear @DavidWiseman, Thank you in advance for your response.
Install the service, I'm going to analyze it like this and I'll tell you about the progress.
