### ISSUE TITLE
DBADash gives error on logshipping while no logshipping is configured

### ISSUE THREAD

**Issue by tvanzeleDelen** [trimble-oss/dba-dash#552]
Hello,

I just installed v2.36 and now I get errors about a database where it's logshipping status is Critical, but this database isn't configured for logshipping. It is however in an AlwaysOn availability group.

**Comment by DavidWiseman** [comment]
DBA Dash will identify databases as log shipping if they are in a restoring or standby state and are not using SIMPLE recovery model or involved in database mirroring.  If the databases are in an availability group the state should be ONLINE and it will be identified as been part of an availability group instead of log shipping.  [See here](https://github.com/trimble-oss/dba-dash/blob/main/DBADashDB/dbo/Views/LogShippingStatus.sql) for the view used.

The databases would have been in the RESTORING state prior to adding to the AG.  If they were added recently, DBA Dash might report them as log shipping until the Databases collection runs again (every hour by default).
If that doesn't explain the issue, check what the state is reported as in sys.databases for that database and check if it matches DBA Dash.

Let me know what you find.

**Comment by tvanzeleDelen** [comment]
Indeed, apparently DBA Dash was just collecting data when the database was being added to the AG.
