### ISSUE TITLE
Feature request: Display the period date range when using "Compare To: Previous Period" in Object Execution screen

### ISSUE THREAD

**Issue by chadbaldwin** [trimble-oss/dba-dash#800]
For example, when viewing the Object Execution page, you put in a Custom date range.

Then you select "Compare To: Previous Period".

I _assume_ that it calculates the diff in the display date range, and then looks back that same amount of time, and I _could_ do that math myself to figure out the comparison date range...but I think it would be tremendously helpful if that was displayed somewhere in the UI.

Thanks!!

**Comment by DavidWiseman** [comment]
Yes - I think it would be useful to display the date range used.  I'll look to add it in a future version.

**Comment by DavidWiseman** [comment]
This information will be shown in the status bar in the next release.  e.g.
![image](https://github.com/trimble-oss/dba-dash/assets/33157668/8de957e2-5145-458f-a43b-6152b2bfc613)

It turns out that previous period was just doing a 60min offset which is only right if you are looking at the last hour - showing the dates made this easier to spot.  This will also be fixed so if you are looking at the last 3 hours, previous period will show the 3 hours prior to that.

**Comment by DavidWiseman** [comment]
This is included in version 3.0.  Note, that there is an upgrade to .NET 8.  🚀
