### ISSUE TITLE
Microsoft Entra Authentication

### ISSUE THREAD

**Issue by EpitomeOfDeath** [trimble-oss/dba-dash#847]
We use Microsoft Entra Authentication for our Azure Elastic pool Dbs.
There is no option for this in login form.

**Comment by DavidWiseman** [comment]
Hi, you can enter a connection string in the source textbox instead of using the Connect dialog to build the connection string.  I think this will allow you to use Entra.  DBA Dash is using the latest SqlClient so it should support this.
[This link](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16) has some connection string examples.

Let me know if it works.

**Comment by jacobgexigo** [comment]
It would be nice to have the configuration GUI allow for the selection of "Microsoft Entra ID with MFA" in the drop down, so we can put in the EID user name and then it would do the normal browser pop to allow the password and MFA for getting the token.  I think this is OAuth.

**Comment by rgrwilloughby** [comment]
We have this working 

We used the command line DBADashConfig -c to set them up 

example connection string below - we've given the VM running the DBA dash server a managed identity and then granted that required access on Azure SQL Servers we want to monitor

  "`ConnectionString": "Data Source=***********.database.windows.net;Encrypt=True;Trust Server Certificate=True;Authentication=ActiveDirectoryManagedIdentity;Application Name=DBADash`",

**Comment by DavidWiseman** [comment]
New connection dialog coming soon...

![image](https://github.com/user-attachments/assets/f7779892-89c4-4512-a9c6-95b97d0c8109)

**Comment by DavidWiseman** [comment]
Included in 3.10 🚀
