### ISSUE TITLE
SelectedTab page is not available for this context

### ISSUE THREAD

**Issue by fvanderhaegen** [trimble-oss/dba-dash#893]
In version 3.51 of DBADash GUI a messagebox 'SelectedTab page is not available for this context' pops-up
when clicking on a 'Test' on the summary screen of  'Checks' page.

![image](https://github.com/trimble-oss/dba-dash/assets/23452667/a04dbc79-718e-4c25-b392-e0308c911dda)

**Comment by DavidWiseman** [comment]
Hi,

Thanks for reporting this issue.  It occurs when loading the summary on the Checks node in the tree and impacts some of the test-level summary links.  As a workaround, you can load the Summary page from the root node and the drill-downs will work from there. I'll get this fixed in the next release.

Thanks,

David

**Comment by DavidWiseman** [comment]
Fixed in 3.5.2 🎉
