### ISSUE TITLE
Bug when there is the same server name

### ISSUE THREAD

**Issue by Drakokorian** [trimble-oss/dba-dash#936]
In DBA Dash, when a server's name is reused for a different server, the application incorrectly merges both servers into a single entity because it relies on the server name for identification. This issue occurs even if the underlying SQL server's name does not change, leading to confusion and inaccurate data. A more robust solution would involve identifying servers using a unique ID rather than the server name.

**Comment by DavidWiseman** [comment]
In the service configuration tool, you can specify a Connection ID which will be used as the unique identifier for an instance.  If you have two servers with the same name you can set them to different values.

Note: In the latest version DBA Dash will auto populate the Connection ID in the service config tool when you add the connection (based on `@@SERVERNAME` (Which you can override as needed).  In older versions the ConnectionId would be left blank and this would be set to `@@SERVERNAME` dynamically.  The change was done because it makes it easier to identify the connection for the new messaging system.

Hope this helps,

David
