### ISSUE TITLE
Inaccurate error 'you must run .Net 6 Desktop' after renaming DBADash.runtimeconfig.json

### ISSUE THREAD

**Issue by vcmcstech** [trimble-oss/dba-dash#97]
If I rename DBADash.runtimeconfig.json and launch DBADash.exe, i get a prompt that .net 6 is not installed.  

![image](https://user-images.githubusercontent.com/35636722/159179253-f5b83812-ca55-4404-9127-cd074e45d51b.png)

Note, .Net Desktop Runtime 6.0.1 is installed.

I click Yes to download, but nothing happens.  

If i rename the file back to original name, the error doesn't occur.  

I was doing this trying to figure out how to reconfigure DBADash to use a different user to connect.  I assumed renaming that config file would prompt me for DBADash server and user again.  I don't see an option for this in the GUI.

**Comment by DavidWiseman** [comment]
Hi, 

The DBADash.runtimeconfig.json file should not be altered or renamed.  The prompt to install the .NET framework is generated from Microsoft code before my application code runs.  Usually, it takes you to the download page.  I tried renaming it and the Yes button didn't do anything for me - probably because it's already installed.

The GUI will use the connection string set for the Destination in the service config tool.  If you want to deploy the front end you can use the zip file in the release labeled GUI_Only which doesn't include the service.  If you launch DBADash.exe you will be prompted to connect the repository database.  Use Windows authentication if possible.  The connection string is stored in ServiceConfig.json the same as for the service - but you will have a simpler json file when deploying the GUI.

Hope this helps,

David

**Comment by vcmcstech** [comment]
simple check for the file could be added upfront.  

could even add validation for the file if it is there.

so what todo here?

there's code in GUI_ONLY to create the file?  do that?

why even require user // pass to be there anyway?  already i keep hearing storing creds there is still insecure even though encrypted.  i think we can prompt for creds if they are not saved.

**Comment by DavidWiseman** [comment]
The service and GUI share a common config.  If you deploy the service you can run the GUI from the same folder and everything just works without requiring additional configuration of the GUI - it just connects to the destination you have set in the config.  
Ideally you use Windows authentication to avoid storing any credentials in the config file.  I would create a windows group for the users that need to access DBA Dash and create a login for that group on the SQL Instance - adding it to the App role in the DBA Dash database.
If you deploy the GUI by itself it prompts for the connection and stores it in a simplified version of the config file.  This might be a problem if you can't use Windows authentication - as the credentials are stored in the config file.  
Getting the app to prompt for credentials might be an option - users would need to input a username/password each time so not seamless like with Windows authentication.  It would avoid storing the password in the config file though.
