### ISSUE TITLE
Add Feature Collect SQL Server Service Account Name

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#978]
DBADASH is not collecting SQL Server Service Account Name and SQL Agent Service Account Name.

**Comment by DavidWiseman** [comment]
The service *display name* and the *associated user account* are available in the `sys.dm_server_services` DMV.  This information isn't currently collected - I might consider adding it in a future version.  
As a workaround it would be possible to create a [custom collection](https://dbadash.com/docs/help/custom-collections/) to capture this information and a [custom report](https://dbadash.com/docs/how-to/create-custom-reports/) to display it.

**Comment by aachaemenes** [comment]
it would be a great check specially with gMSA account. we want to know which server is not setup correctly with gMSA and it will raise the flag.

**Comment by DavidWiseman** [comment]
Thanks - the additional context of what you are using this for is helpful.  It makes sense to use gMSA accounts and being able to validate this in DBA Dash would be useful.

**Comment by Drakokorian** [comment]
This would be handy for us as well great idea.

**Comment by DavidWiseman** [comment]
This will be available in the next version

![image](https://github.com/user-attachments/assets/a39e06f0-0317-4001-b2fe-2a6d23bce2d9)

**Comment by dv2287** [comment]
Hi David,

this feature is great. Is it possible to include other SQL Services that are running outside of database engine (SSIS, SSAS, SSRS, PowerBI Report Server,PolyBase services, ...)? I know that this information is not available in DMV's, but maybe WMI collection can help. I have adapted some online script that checks status of these services from database engine (with xp_servicecontrol and xp_regread stored procedures and additionally with xp_cmdshell for SSAS) and implemented it as a custom check on several test servers, but I like your "out-of-the-box" solution more since it does not require interventions in monitored instances and it contains more details.
