### ISSUE TITLE
The following page seems to not exist 

### ISSUE THREAD

**Issue by Drakokorian** [trimble-oss/dba-dash#980]
I am migrating to a new server for better performance.

but the following page seems to not exist https://dbadash.com/docs/setup/move-service/

and on the quickstart page  "If you select an existing database it will need to be completely blank with no existing objects created." 

What happens if there is objects ?

Set a destination connection
💡
The destination connection is the SQL instance where your DBA Dash repository database is to be located. By default this is set to DBADashDB and the database will be created automatically when the service starts. If you select an existing database it will need to be completely blank with no existing objects created.

**Comment by DavidWiseman** [comment]
Hi,  Thank you for reporting this issue.  The issue occurred due to a website upgrade which changed how the URL was being generated (based on title rather than folder name).  This should be fixed now - try a ctrl+refresh if you still have issues.

If you select an existing database it will do a validation check to ensure that it's a DBA Dash repository database you are connecting to.  If the database is empty it will create the schema.  If the database is an existing DBA Dash repository database that's also OK.  
If the database already has objects and it doesn't pass the validation check it will fail (to prevent it from deploying the schema to some user database for example)
